Task-25-Linkedin-Auth-Front-End-/-Back-End
fe-team-itechart/project-x-client pull request #33
Opened 2019-08-27 15:22 UTC by melonholy

2019-08-28 06:55 UTC, slavasgod requested changes

2019-08-28 06:55 UTC, slavasgod commented on src/containers/auth/login/index.js
> +    const googleURL = `http://localhost:8080/api/users/auth/google`;
URL hardcode?

2019-08-28 06:55 UTC, slavasgod commented on src/containers/auth/login/index.js
> +    if (this.queryParams.tokenGoogle) {
`componentWillMount` is unsafe and deprecated, remove it

2019-08-28 06:55 UTC, slavasgod commented on src/containers/auth/login/index.js
> +import {
Fix imports order: base react libraries - custom react libraries - your components - styles. Separate every group by whitespace. Check it in all your files

2019-08-28 06:55 UTC, slavasgod commented on src/containers/auth/styles.module.scss
> +  color: #737373;
magic colors?

2019-08-28 06:55 UTC, slavasgod commented on src/containers/auth/styles.module.scss
> +    background-color: #e5e5e5;
magic color?

2019-08-28 06:55 UTC, slavasgod commented on src/containers/auth/styles.module.scss
> +  .googleButtonIcon {
we don't use camelCase in css

2019-08-28 06:55 UTC, slavasgod commented on src/containers/auth/styles.module.scss
> +    font-family: 'Roboto', arial, sans-serif;
we have variables for fonts

2019-08-28 06:55 UTC, slavasgod commented on src/containers/auth/login/index.js
>  export default connect(
If you don't use mapStateToProps, replace it on `null`

2019-08-28 06:55 UTC, slavasgod commented on package.json
> +    "linkedin-login-for-react": "^1.2.3",
I didn't find place, where you used this library. If you didn't use this library - remove it

2019-08-28 08:12 UTC, slavasgod commented on src/containers/auth/login/index.js
> +const mapStateToProps = null;
I mean pass null into connect function:
```
export default connect(
  null,
  mapDispatchToProps
)(Login);
```

2019-08-28 12:48 UTC, OlegPanasyuk commented on src/containers/auth/login/index.js
> +              <div className={styles.google_button}>
Use destruction for styles

2019-08-28 12:51 UTC, universezzz requested changes

2019-08-28 12:51 UTC, universezzz commented on src/containers/auth/login/index.js
> +                <span className={styles.google_button_text}>
Why did you use `<span>` for google and linkedin auth? This tag made to wrap small blocks or decorative elements of a web page. Please, use `<button>`.

2019-08-28 12:51 UTC, universezzz commented on src/containers/auth/login/index.js
> +    const { location, history } = this.props;
if you destructed location and history, why did you not destruct googleLoginRequest and linkedInLoginRequest from props?

2019-08-28 12:51 UTC, universezzz commented on src/containers/auth/login/index.js
> +    const linkedInURL = `api/users/auth/linkedin`;
I don't know, but maybe, isn't a good idea, to make variables for google and linkedin urls? You can insert string presentetion of url to the href parameter of link right away. <`a href={'api/users/auth/google'}>`. First of all, you don't allocate memory for variable.

2019-08-28 12:51 UTC, universezzz commented on src/containers/auth/register/index.js
> +  componentDidMount() {
if you destructed location and history, why did you not destruct googleLoginRequest and linkedInLoginRequest from props?

2019-08-28 15:11 UTC, melonholy commented on src/containers/auth/login/index.js
> +      this.props.linkedInLoginRequest(parsed.tokenLinkedin);
make it as one united token

2019-08-28 15:11 UTC, melonholy commented on src/containers/auth/register/index.js
> +    if (parsed.tokenGoogle) {
make HOC for google/linkedin login and provide as children needed inputs and button. CC @universezzz

2019-08-28 15:11 UTC, melonholy commented on src/containers/auth/register/index.js
> +    if (parsed.tokenLinkedin) {
also get rid of if's

2019-08-28 15:11 UTC, melonholy commented on src/containers/auth/register/index.js
> +                  <svg viewBox="0 0 366 372" xmlns="http://www.w3.org/2000/svg">
add svg loader to webpack and create svg file -> import him here as component

2019-09-03 09:45 UTC, melonholy commented on src/containers/auth/login/index.js
> +                  <LinkedIn />
add icon to name

2019-09-03 09:45 UTC, melonholy commented on src/services/auth.js
> +  const decoded = jwt_decode(res.payload);
remove jwt-decode lib from front-end. send get request for user data with this token.

2019-09-03 09:45 UTC, melonholy commented on src/services/auth.js
> +  localStorage.setItem('token', res.payload);
write some wrapper to local storage

2019-09-03 09:45 UTC, melonholy commented on src/services/auth.js
> +  return decoded;
newline before return

2019-09-03 09:45 UTC, melonholy commented on src/services/auth.js
> +  setAuthToken(res.payload);
rewrite token flow

2019-09-04 13:06 UTC, slavasgod requested changes

2019-09-04 13:06 UTC, slavasgod commented on package.json
> +    "history": "^4.9.0",
`@svgr/webpack` and `babel-plugin-named-asset-import` should be in devDependencies

2019-09-05 08:10 UTC, OlegPanasyuk approved these changes

2019-09-05 08:55 UTC, slavasgod approved these changes

2019-09-05 11:31 UTC, merged