Task-11-profile-courses-ui
fe-team-itechart/project-x-client pull request #35
Opened 2019-08-29 14:41 UTC by sergevei

2019-08-30 18:46 UTC, OlegPanasyuk requested changes

2019-08-30 18:46 UTC, OlegPanasyuk commented on src/containers/profile/coursesTab/courseCard.jsx
> +import { Link } from 'react-router-dom';
Check the order of importing the components and libs. Ask Slava about the right order of import

2019-08-30 18:46 UTC, OlegPanasyuk commented on src/containers/profile/coursesTab/index.jsx
> +        </div>
Maybe it useful to create HOC that will return the necessary component. It will implement models and reuseable components/

2019-08-30 18:46 UTC, OlegPanasyuk commented on src/containers/profile/coursesTab/index.jsx
> +            link={course.courseLink}
The same thing with CourseCards. They so similar and you can join then into HOC

2019-08-30 18:46 UTC, OlegPanasyuk commented on src/containers/profile/coursesTab/yourCourseCard.jsx
> +};
I like your style of code.

2019-09-03 05:44 UTC, slavasgod requested changes

2019-09-03 05:44 UTC, slavasgod commented on src/containers/profile/coursesTab/styles.module.scss
> +  }
Maybe 340 or 345?)

2019-09-03 05:44 UTC, slavasgod commented on src/containers/profile/coursesTab/yourCourseCard.jsx
> +export const YourCourseCard = ({ type, img, name, link }) => {
You can pass here an object with these fields, like:
`export const YourCourseCard = ({ course }) => {}`
Use it like `course.type` etc. And in your parent component you can call it like:
`<YourCourseCard course={course} />`
Also I think it is better to change name of this component

2019-09-03 05:44 UTC, slavasgod commented on src/containers/profile/profile.js
Change import order

2019-09-03 05:44 UTC, slavasgod commented on src/containers/profile/coursesTab/styles.module.scss
> +      transition: 0.3s;
Use scss syntax:
```
.img_block {
  &:hover { }
}
```

2019-09-03 05:44 UTC, slavasgod commented on src/containers/profile/coursesTab/courseCard.jsx
> +    card,
Same as YourCourseCard

2019-09-11 11:22 UTC, universezzz requested changes

2019-09-11 11:22 UTC, universezzz commented on src/containers/profile/coursesTab/addNewCourseCard.jsx
> +        <p>+</p>
use `<span>` instead of `<p>` for small elements

2019-09-11 11:22 UTC, universezzz commented on src/containers/profile/coursesTab/addNewCourseCard.jsx
> +      <p>Add new course</p>
In the future, Is it not a button?

2019-09-11 11:22 UTC, universezzz commented on src/containers/profile/coursesTab/createdCourseCard.jsx
> +        <div className={button}>Continue</div>
In the future, Is it not a button?

2019-09-11 11:22 UTC, universezzz commented on src/containers/profile/coursesTab/createdCourseCard.jsx
> +      <div className={img_block} style={{ backgroundImage: `url(${img})` }} />
Maybe, Is it better to use `img` tag?

2019-09-11 11:22 UTC, universezzz commented on src/containers/profile/coursesTab/findNewCourseCard.jsx
> +        <p>+</p>
Rewrite as well as in the commit above.

2019-09-11 11:22 UTC, universezzz commented on src/containers/profile/coursesTab/styles.module.scss
> +      background-size: auto 100%;
use one prop background

2019-09-11 11:22 UTC, universezzz commented on src/containers/profile/coursesTab/styles.module.scss
> +    border-radius: 5px;
dublicate border-radius

2019-09-12 11:38 UTC, sergevei commented on src/containers/profile/coursesTab/createdCourseCard.jsx
> +      <div className={img_block} style={{ backgroundImage: `url(${img})` }} />
It is a wrong way to use `img` tag here

2019-09-13 10:22 UTC, slavasgod approved these changes

2019-09-13 10:50 UTC, slavasgod approved these changes

2019-09-13 11:14 UTC, universezzz approved these changes

2019-09-13 11:15 UTC, merged