Task-6-drop-down-log-out-ui-front-end
fe-team-itechart/project-x-client pull request #38
Opened 2019-09-11 11:08 UTC by slavasgod

2019-09-11 12:49 UTC, melonholy requested changes

2019-09-11 12:49 UTC, melonholy commented on src/containers/header/index.js
> +  const { logOutRequest } = props;
unite this in one row

2019-09-12 07:25 UTC, universezzz approved these changes

2019-09-12 07:25 UTC, universezzz commented on src/containers/header/index.js
> +const mapStateToProps = state => ({ props: state });
Perhaps, is `props: state.user` better instead of receiving whole state?

2019-09-12 07:25 UTC, universezzz commented on src/containers/header/index.js
> +              <div className={styles.button} onClick={() => logOutRequest()}>
Use `button` instead of `div`

2019-09-12 07:34 UTC, melonholy approved these changes

2019-09-12 07:34 UTC, merged