Bug-14: Login-Validation
fe-team-itechart/project-x-client pull request #47
Opened 2019-09-19 12:35 UTC by melonholy

2019-09-19 12:46 UTC, universezzz commented on src/containers/auth/login/index.js
> +  errors: state.user.errors,
remove it

2019-09-19 14:00 UTC, OlegPanasyuk requested changes

2019-09-19 14:00 UTC, OlegPanasyuk commented on src/containers/auth/login/index.js
> +            {(errors.email || errors.type === 'email') && (
I think it necessary to add your own status codes to manage error validation/

2019-09-19 14:00 UTC, OlegPanasyuk commented on src/containers/auth/login/index.js
> +                <span className={styles.linkedin_button_text}>
Please, destruct this styles.

2019-09-20 07:58 UTC, slavasgod approved these changes

2019-09-20 09:46 UTC, universezzz approved these changes

2019-09-20 10:01 UTC, OlegPanasyuk approved these changes

2019-09-20 10:03 UTC, merged