Bug 23 carousel arrows
fe-team-itechart/project-x-client pull request #60
Opened 2019-09-25 14:05 UTC by melonholy

2019-09-26 07:33 UTC, OlegPanasyuk approved these changes

2019-09-26 07:33 UTC, OlegPanasyuk commented on src/containers/couresCarousel/index.js
>            <AliceCarousel
Maybe `ref={el => this.Carousel = el}` needs to be replased by `ref={this.CarouselRef}`?

React.CreateRef() is intended for such goals like animation.

2019-09-26 07:33 UTC, OlegPanasyuk commented on src/containers/couresCarousel/index.js
>      );
So, remove the unnecessary code bonded with the Redux.
```
const mapStateToProps = state => ({});

const mapDispatchToProps = {};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CoursesCarousel);
```

2019-09-26 07:33 UTC, OlegPanasyuk commented on src/containers/couresCarousel/index.js
> +  370: {
Look, we have such endpoints for CSS.
```
$width-xs: 320px;
$width-sm: 576px;
$width-md: 768px;
$width-lg: 992px;
$width-xl: 1200px;
```

Maybe it useful to have such endpoints into the carousel.

2019-09-26 07:33 UTC, OlegPanasyuk commented on src/validation/auth.js
> +  console.log(passwordValidate);
Remove Console executing

2019-09-27 06:33 UTC, slavasgod requested changes

2019-09-27 06:33 UTC, slavasgod commented on src/containers/couresCarousel/styles.module.scss
>    }
You hide arrows on mobile version, so now it is hard to understand, that this is a carousel, it looks like a single image.

2019-09-27 10:57 UTC, slavasgod approved these changes

2019-09-27 11:34 UTC, merged