Task-104-Getting-courses-for-carousel
fe-team-itechart/project-x-client pull request #66
Opened 2019-10-04 06:11 UTC by melonholy

2019-10-04 12:13 UTC, universezzz requested changes

2019-10-04 12:13 UTC, universezzz commented on src/components/couresCarousel/index.js
Pls, move variable 'responsive' to the folder 'constants'

2019-10-04 12:13 UTC, universezzz commented on src/components/couresCarousel/index.js
> +    getCoursesForCarousel().then(courses => {
rewrite to async/await syntax pls

2019-10-07 07:22 UTC, OlegPanasyuk requested changes

2019-10-07 07:22 UTC, OlegPanasyuk commented on src/components/couresCarousel/index.js
> +    getCoursesForCarousel().then(courses => {
And add error processing by try/catch

2019-10-15 09:41 UTC, universezzz commented on src/services/courses.js
> +    url: links.corsesCarouselRoute,
courses

2019-10-15 09:41 UTC, universezzz approved these changes

2019-10-15 10:37 UTC, OlegPanasyuk approved these changes

2019-10-15 11:14 UTC, merged