Task-3: main-page-slider
fe-team-itechart/project-x-client pull request #69
Opened 2019-10-14 09:46 UTC by sergevei

2019-10-14 13:37 UTC, slavasgod requested changes

2019-10-14 13:37 UTC, slavasgod commented on src/containers/mainPage/index.js
> +          <h1>{item.header}</h1>
You don't use `i`, remove it

2019-10-15 07:26 UTC, slavasgod approved these changes

2019-10-15 13:36 UTC, melonholy approved these changes

2019-10-17 08:27 UTC, merged