feature-11/socials
fe-team-itechart/project-x-client pull request #70
Opened 2019-10-14 11:48 UTC by sergevei

…component for preview

2019-10-14 13:41 UTC, slavasgod requested changes

2019-10-14 13:41 UTC, slavasgod commented on src/components/socials/styles.module.scss
> +  display: flex;
we have white color in constants, use it

2019-10-15 07:26 UTC, slavasgod approved these changes

2019-10-15 08:17 UTC, universezzz approved these changes

2019-10-17 08:16 UTC, merged